name: Flutter Web

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Web
    env:
      myy_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release
    - run:
        cd build/web
        git init
        git config --global user.email craig@oppkey.com
        git config --global user.name craig
        git status
        git remote add origin https://${{secrets.commit_secret}}@github.com/codetricity/flutter-web.git
        git checkout -b gh-pages
        git add --all
        git commit -m "update"
        git push origin gh-pages -f

